services:
  checkmk:
    container_name: checkmk
    image: checkmk/check-mk-raw:latest
    restart: unless-stopped
    environment:
      CMK_SITE_ID: ${CMK_SITE_ID:-monitoring}
      CMK_PASSWORD: ${CMK_PASSWORD}
    volumes:
      - ./sites:/omd/sites
    tmpfs:
      - /opt/omd/sites/${CMK_SITE_ID:-monitoring}/tmp:uid=1000,gid=1000
    #Puertos expuestos para acceso directo (opcional, se recomienda usar proxy inverso)  
    #ports:
    # - 5000:5000
    
# añadir estas líneas al final del archivo para proxy inverso 
networks:
  default:
    external: true
    name: proxy